name: dcgm
base: core24
version: 1.0
summary: Snap for NVIDIA dcgm and dcgm-exporter
license: Apache-2.0
contact: solutions-engineering@lists.canonical.com
description: |
  This snap includes NVIDIA dcgm and dcgm-exporter to provide GPU monitoring via Prometheus metrics.
grade: stable
confinement: strict

package-repositories:
  - type: apt
    path: /
    formats: [deb]
    key-id: EB693B3035CD5710E231E123A4B469963BF863CC
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64

apps:
  dcgm-exporter:
    command: bin/dcgm-exporter -f $SNAP/etc/dcgm-exporter/dcp-metrics-included.csv
    plugs:
      - network-bind
      - opengl
  dcgmi:
    command: usr/bin/dcgmi
    plugs:
      - opengl
  nv-hostengine:
    command: usr/bin/nv-hostengine -n --service-account nvidia-dcgm -p 8888
    plugs:
      - network-bind
      - opengl
    daemon: simple
    restart-condition: on-abort
    environment:
      DCGM_HOME_DIR: "${SNAP_DATA}/nvidia-dcgm"

parts:
  dcgm-exporter:
    plugin: go
    stage-packages: [datacenter-gpu-manager]
    build-snaps:
      - go
    source: https://github.com/NVIDIA/dcgm-exporter.git
    source-type: git
    override-build: |
      craftctl default
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/dcgm-exporter
      cp ${SNAPCRAFT_PROJECT_DIR}/config/dcp-metrics-included.csv $SNAPCRAFT_PART_INSTALL/etc/dcgm-exporter/dcp-metrics-included.csv
